### PR TITLE
Basic image resize implementation.

### PR DESCRIPTION
**Pull request by mareksubocz**
First implementation of #36. Applied image resize to val and test datasets as well.

Feel free to change it up or even throw out altogether. Let me know what you think :)

### CODE REVIEW

**Comment by tlpss** [comment]
@mareksubocz  thanks for the contribution, I will take a look soon!

**Comment by tlpss** [comment]
hi @mareksubocz

Sorry for the late reply! 

Your PR looks good but for now I am not going to merge it because I am thinking about doing a major refactor that should facilitate custom preprocessing steps etc instead of having to include them all in the codebase. 

I will definitely use your code as an example/inspiration. So thanks for that!

**Comment by mareksubocz** [comment]
No problem, good luck with the refactor!

**Comment by ExtReMLapin** [comment]
Working on a PR that does that but on a // 32 factor because of model architecture restrictions

**Pull request closed without merging**
