### PR TITLE
added 40x faster extraction method

### PR DESCRIPTION
**Pull request by lucasvandijck**

### CODE REVIEW

**Comment by lucasvandijck** [comment]
Note that my algorithm outputs a Tensor on the same device as the input heatmap. This is probably not yet compatible with the existing post-processing code.

**Comment by tlpss** [comment]
Thanks for the contribution @lucasvandijck. 

I think we need to add some tests to see if your implementation is equivalent to the skimage implementation and probably also fix the output format looking at the pytest results.

 I won't have time for this in the coming week(s) and I'm guessing you won't either so we'll see who finds some time later on to fix the above so that we can merge this improvement. 

PS: does the 40x also include the time to copy data to the CPU?

**Comment by lucasvandijck** [comment]
> I think we need to add some tests to see if your implementation is equivalent to the skimage implementation and probably also fix the output format looking at the pytest results.

I am not sure the implementation is 100% equivalent looking at the skimage source code. However, the main functionality is definitely similar and I don't expect large discrepancies. Testing is definitely needed, but I don't know enough about your testing strategy to implement it cleanly.

> I won't have time for this in the coming week(s) and I'm guessing you won't either so we'll see who finds some time later on to fix the above so that we can merge this improvement.

Yes, my main goal was just adding the code so it wouldn't get lost somewhere.

> PS: does the 40x also include the time to copy data to the CPU?

Yes, I simply ran the test on our iPC (i7-10700TE and T1000 GPU) and added a synchronised PyTorch timer. Original times were steady around 750ms for 1920x1184 images, now the times fluctuate more, but they stay below 20ms 99% of the times, with a mean around 14ms.

**Comment by tlpss** [comment]
@lucasvandijck 

I've finally found some time to take a look at this. I tested your code and it is indeed a looot faster than the scipy CPU implementation. I think I found a bug though: by deleting the 'NMS entries' in the candidate list, you also might delete neighbours from other entries in the candidate list that have yet to be checked. This leads to false positives if those entries had a higher score. 

After some thinking and looking around, I've implemented it differently. Speedups are about the same (5x - 70x depending on batch_size, number of channels and max_keypoints)

Thanks again for the starting point!

**Pull request closed without merging**
